UNLOCK TABLES;

DROP DATABASE IF EXISTS Autosocietron_DB;
CREATE DATABASE Autosocietron_DB;

USE Autosocietron_DB;

DROP TABLE IF EXISTS PROFILE;
CREATE TABLE PROFILE (
	username VARCHAR(15) NOT NULL,
	password VARCHAR(20) NOT NULL,
	firstName VARCHAR(35) NOT NULL,
	surname VARCHAR(35) NOT NULL,
	dateOfBirth DATE NOT NULL,
	gender ENUM("Male","Female") NOT NULL,
	bio VARCHAR(255),
	avatar VARCHAR(255) NOT NULL,
	city VARCHAR(50),
	country VARCHAR(50) NOT NULL,
	interest1 SET("Computing","Science","Sport","Food") NOT NULL,
	interest2 SET("Computing","Science","Sport","Food") NOT NULL,
	interest3 SET("Computing","Science","Sport","Food") NOT NULL,
	TTP INT NOT NULL,
	TTPJ INT NOT NULL,
	LTP INT NOT NULL,
	SPL INT NOT NULL,
	LTPINT1 INT NOT NULL,
	LTPINT2 INT NOT NULL,
	LTPINT3 INT NOT NULL,
	LTPNEWLOC INT NOT NULL,
	LTPEVENT INT NOT NULL,
	LTPWEATHER INT NOT NULL,
	LTPNEWS INT NOT NULL,
	LTPFLR INT NOT NULL,
	LTPPHOTO INT NOT NULL,
	CONSTRAINT pk_PROFILE PRIMARY KEY (username)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS POST;
CREATE TABLE POST (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	postBody VARCHAR(255) NOT NULL,
	tags VARCHAR(50),
	dateTimePosted DATETIME NOT NULL DEFAULT NOW(),
	postType SET("TEXT","LOCATION","EVENT","WEATHER","NEWS","FILLER","PHOTO") NOT NULL,
	USER_username VARCHAR(15),
	CONSTRAINT pk_POST PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ACQUAINTANCE;
CREATE TABLE ACQUAINTANCE (
	USER_username VARCHAR(15) NOT NULL,
	connectedUsername VARCHAR(15) NOT NULL,
	CONSTRAINT pk_ACQUAINTANCE PRIMARY KEY (USER_username, connectedUsername)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


LOCK TABLES 
	PROFILE WRITE, 
	POST WRITE, 
	ACQUAINTANCE WRITE;

ALTER TABLE ACQUAINTANCE
	ADD CONSTRAINT fk_ACQUANTANCE_PROFILE FOREIGN KEY (USER_username) REFERENCES PROFILE (username) ON DELETE CASCADE;

ALTER TABLE POST 
	ADD CONSTRAINT fk_POST_PROFILE FOREIGN KEY (USER_username) REFERENCES PROFILE (username) ON DELETE CASCADE;

UNLOCK TABLES;

#Testing profile
INSERT INTO `autosocietron_db`.`profile`
	VALUES ('shood', 'password', 'Sam', 'Hood', '1988-12-22', 'Male', 'I dunno lol', 'NA', 'Dundee', 'Scotland', 'Computing', 'Science', 'Food', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5');

